version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/app
  redis:
    image: "redis:alpine"
  mqtt:
    image: "eclipse-mosquitto:1.5.3"
    ports:
     - "1883:1883"