version: '3.1'
services:
  web:
    build: ./ium-server-image/
    ports:
     - "5000:5000"
     - "80:8080"
    volumes:
     - .:/ium-server-image/app
  mqtt:
    image: "eclipse-mosquitto:1.5.3"
    ports:
     - "1883:1883"